# This is the nebula host example configuration file.
# At a minimum, you will need to edit the static_host_map and lighthouse: hosts variables to match your environment.
# For a complete list of options and settings, see https://www.defined.net/nebula/config/ and see the full config.yml example.

pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/host.crt
  key: /etc/nebula/host.key

listen:
  host: 0.0.0.0
  port: 0

tun:
  dev: nebula1

firewall:
  outbound:
    # Allow all outbound traffic from this node
    - port: any
      proto: any
      host: any

  inbound:
    # Allow icmp between any nebula hosts
    - port: any
      proto: icmp
      host: any

static_host_map:
  "192.168.100.1": ["100.64.22.11:4242"]

lighthouse:
  hosts:
    - "192.168.100.1"

punchy:
  punch: true
